"""
LullabAI Video Generation — Evaluation Script
================================================
Computes 5 metrics for the video generation pipeline:

  Metric 5: Audio-Visual Sync Error      — timing accuracy of scene clips
  Metric 6: Prompt Adherence (CLIP-like)  — image ↔ text alignment via Gemini
  Metric 7: Image Quality (Sharpness)     — before vs after ESRGAN upscaling
  Metric 8: Pipeline Latency Breakdown    — time per stage
  Metric 9: Speaking Rate (WPM)           — narration speed for children

Usage:
    python evaluate_video.py <path_to_evaluation_data.json>

    The evaluation_data.json is auto-generated by generate_video.py
    in the temp directory (e.g., output_videos/temp_<story_id>/evaluation_data.json)

Output:
    video_evaluation_results.json (saved alongside the evaluation_data.json)
"""

import sys
import os
import json
import subprocess

# Force UTF-8 output on Windows to prevent UnicodeEncodeError
if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FFMPEG_PATH = os.path.join(SCRIPT_DIR, "ffmpeg.exe")
if not os.path.exists(FFMPEG_PATH):
    FFMPEG_PATH = "ffmpeg"


# ═══════════════════════════════════════════════════════════════════════════════
# METRIC 5: Audio-Visual Sync Error
# ═══════════════════════════════════════════════════════════════════════════════

def get_media_duration(file_path: str) -> float:
    """Get duration of an audio or video file in seconds using ffmpeg."""
    cmd = [
        FFMPEG_PATH, "-i", file_path,
        "-f", "null", "-"
    ]
    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=30
        )
        # Duration is in stderr for ffmpeg
        output = result.stderr
        for line in output.split("\n"):
            if "Duration:" in line:
                # Format: Duration: 00:00:12.34, ...
                time_str = line.split("Duration:")[1].split(",")[0].strip()
                parts = time_str.split(":")
                hours = float(parts[0])
                minutes = float(parts[1])
                seconds = float(parts[2])
                return hours * 3600 + minutes * 60 + seconds
    except Exception as e:
        print(f"  [Warn] Could not get duration for {file_path}: {e}")
    return 0.0


def eval_av_sync(scene: dict) -> dict:
    """
    Metric 5: Audio-Visual Sync Error
    Compares the audio duration with the actual video clip duration.
    The video should match the audio length exactly (due to -shortest flag).
    """
    audio_path = scene.get("audio_path", "")
    vid_path = scene.get("vid_path", "")

    audio_dur = get_media_duration(audio_path) if os.path.exists(audio_path) else 0
    video_dur = get_media_duration(vid_path) if os.path.exists(vid_path) else 0

    sync_error = abs(video_dur - audio_dur) if audio_dur > 0 else -1

    return {
        "audio_duration_sec": round(audio_dur, 3),
        "video_duration_sec": round(video_dur, 3),
        "sync_error_sec": round(sync_error, 3),
        "rating": "perfect" if sync_error < 0.1 else ("good" if sync_error < 0.5 else "poor"),
    }


# ═══════════════════════════════════════════════════════════════════════════════
# METRIC 6: Prompt Adherence (CLIP-like via Gemini Multimodal)
# ═══════════════════════════════════════════════════════════════════════════════

_clip_model = None
_clip_processor = None

def get_clip_score(image_path: str, text: str) -> float:
    global _clip_model, _clip_processor
    
    # Lazy import so we don't slow down the script if this metric isn't reached
    import torch
    from PIL import Image
    from transformers import CLIPProcessor, CLIPModel
    import logging
    
    # Suppress transformers warnings
    logging.getLogger("transformers").setLevel(logging.ERROR)

    if _clip_model is None:
        print("  [CLIP] Loading model (openai/clip-vit-base-patch32) for the first time...")
        model_id = "openai/clip-vit-base-patch32"
        _clip_model = CLIPModel.from_pretrained(model_id)
        _clip_processor = CLIPProcessor.from_pretrained(model_id)
        
    image = Image.open(image_path).convert("RGB")
    inputs = _clip_processor(text=[text], images=image, return_tensors="pt", padding=True)
    
    with torch.no_grad():
        outputs = _clip_model(**inputs)
        
    # Get normalized features to compute cosine similarity
    image_embeds = outputs.image_embeds
    text_embeds = outputs.text_embeds
    
    image_embeds = image_embeds / image_embeds.norm(dim=-1, keepdim=True)
    text_embeds = text_embeds / text_embeds.norm(dim=-1, keepdim=True)
    
    cosine_sim = torch.matmul(image_embeds, text_embeds.t()).item()
    
    # Scale to typical 0-1 range for consistency
    # CLIP cosine similarities usually fall between 0.15 and 0.35, but let's just return the raw score clamped
    return round(max(0.0, min(1.0, cosine_sim)), 3)

def eval_prompt_adherence(scene: dict, api_key: str = None) -> dict:
    """
    Metric 6: Prompt Adherence
    Uses OpenAI's CLIP model to compute semantic similarity between the generated 
    image and the prompt text.
    """
    img_path = scene.get("img_path", "")
    prompt = scene.get("prompt_used", "")

    if not os.path.exists(img_path) or not prompt:
        return {"score": -1, "method": "skipped", "reason": "missing image or prompt"}

    try:
        score = get_clip_score(img_path, prompt)
        return {"score": score, "method": "clip_score"}
    except Exception as e:
        print(f"  [Warn] CLIP evaluation failed: {e}. Falling back to heuristic.")
        
    # ── Fallback: keyword heuristic ───────────────────────────────────────────
    keywords = ["storybook", "children", "magical", "colorful", "whimsical", "illustration"]
    prompt_lower = prompt.lower()
    matches = sum(1 for k in keywords if k in prompt_lower)
    heuristic_score = min(1.0, matches / len(keywords) + 0.4)

    return {"score": round(heuristic_score, 3), "method": "keyword_heuristic"}


# ═══════════════════════════════════════════════════════════════════════════════
# METRIC 7: Image Quality (Sharpness — before vs after ESRGAN)
# ═══════════════════════════════════════════════════════════════════════════════

def measure_sharpness(image_path: str) -> float:
    """
    Compute a sharpness score using PIL edge detection.
    Higher value = sharper image with more defined edges.
    Uses FIND_EDGES filter + standard deviation of pixel intensities.
    """
    try:
        from PIL import Image, ImageFilter, ImageStat
        img = Image.open(image_path).convert("L")  # Convert to grayscale
        edges = img.filter(ImageFilter.FIND_EDGES)
        stat = ImageStat.Stat(edges)
        # Use standard deviation of edge intensities — higher = sharper
        return round(stat.stddev[0], 2)
    except Exception as e:
        print(f"  [Warn] Could not measure sharpness for {image_path}: {e}")
        return -1


def eval_image_quality(scene: dict) -> dict:
    """
    Metric 7: Image Quality
    Compares sharpness of original (pre-ESRGAN) vs enhanced (post-ESRGAN) image.
    Reports improvement ratio.
    """
    img_original = scene.get("img_original_path", "")
    img_enhanced = scene.get("img_path", "")

    original_sharpness = measure_sharpness(img_original) if os.path.exists(img_original) else -1
    enhanced_sharpness = measure_sharpness(img_enhanced) if os.path.exists(img_enhanced) else -1

    if original_sharpness > 0 and enhanced_sharpness > 0:
        improvement = round(enhanced_sharpness / original_sharpness, 2)
    else:
        improvement = -1

    # Get image dimensions
    try:
        from PIL import Image
        orig_size = Image.open(img_original).size if os.path.exists(img_original) else (0, 0)
        enh_size = Image.open(img_enhanced).size if os.path.exists(img_enhanced) else (0, 0)
    except Exception:
        orig_size = (0, 0)
        enh_size = (0, 0)

    return {
        "original_sharpness": original_sharpness,
        "enhanced_sharpness": enhanced_sharpness,
        "improvement_ratio": improvement,
        "original_resolution": f"{orig_size[0]}x{orig_size[1]}",
        "enhanced_resolution": f"{enh_size[0]}x{enh_size[1]}",
    }


# ═══════════════════════════════════════════════════════════════════════════════
# METRIC 8: Pipeline Latency Breakdown (read from timing data)
# ═══════════════════════════════════════════════════════════════════════════════

def eval_latency(scene: dict) -> dict:
    """
    Metric 8: Pipeline Latency Breakdown
    Returns the per-stage timing data captured by generate_video.py.
    """
    timing = scene.get("timing", {})
    return {
        "fetch_sec": timing.get("fetch_sec", -1),
        "upscale_sec": timing.get("upscale_sec", -1),
        "ffmpeg_sec": timing.get("ffmpeg_sec", -1),
        "total_sec": timing.get("total_sec", -1),
    }


# ═══════════════════════════════════════════════════════════════════════════════
# METRIC 9: Speaking Rate (WPM)
# ═══════════════════════════════════════════════════════════════════════════════

def eval_speaking_rate(scene: dict) -> dict:
    """
    Metric 9: Speaking Rate
    Calculates words-per-minute from the audio duration and word count.
    Ideal for children aged 2-8: 120-150 WPM.
    """
    audio_path = scene.get("audio_path", "")
    word_count = scene.get("word_count", 0)

    audio_dur = get_media_duration(audio_path) if os.path.exists(audio_path) else 0

    if audio_dur > 0 and word_count > 0:
        wpm = round((word_count / audio_dur) * 60, 1)
    else:
        wpm = -1

    if wpm > 0:
        if 100 <= wpm <= 160:
            rating = "ideal"     # Perfect for children
        elif 80 <= wpm <= 180:
            rating = "acceptable"
        else:
            rating = "too_fast" if wpm > 180 else "too_slow"
    else:
        rating = "unknown"

    return {
        "word_count": word_count,
        "audio_duration_sec": round(audio_dur, 2),
        "wpm": wpm,
        "target_wpm": "120-150",
        "rating": rating,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN — Run all metrics
# ═══════════════════════════════════════════════════════════════════════════════

def main(eval_data_path: str):
    with open(eval_data_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    story_id = data.get("story_id", "unknown")
    scenes = data.get("scenes", [])
    total_pipeline_sec = data.get("total_pipeline_sec", -1)

    # Try to load Gemini API key from .env
    gemini_key = None
    try:
        from dotenv import load_dotenv
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(eval_data_path)))
        load_dotenv(os.path.join(base_dir, ".env"))
    except ImportError:
        pass
    gemini_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_AI_API_KEY")

    print(f"\n{'='*70}")
    print(f"  LullabAI Video Evaluation - Story: {story_id}")
    print(f"  Scenes: {len(scenes)} | Total pipeline: {total_pipeline_sec}s")
    print(f"{'='*70}\n")

    results = {
        "story_id": story_id,
        "total_pipeline_sec": total_pipeline_sec,
        "scene_count": len(scenes),
        "scenes": [],
        "averages": {},
    }

    # Accumulators for averages
    sync_errors = []
    clip_scores = []
    sharpness_improvements = []
    fetch_times = []
    upscale_times = []
    ffmpeg_times = []
    wpms = []

    for scene in scenes:
        idx = scene["scene_index"]
        print(f"-- Scene {idx}: \"{scene['sentence'][:50]}...\"")

        # Metric 5
        av_sync = eval_av_sync(scene)
        print(f"   [M5] AV Sync Error:    {av_sync['sync_error_sec']}s ({av_sync['rating']})")

        # Metric 6
        clip = eval_prompt_adherence(scene, gemini_key)
        print(f"   [M6] Prompt Adherence: {clip['score']} ({clip['method']})")

        # Metric 7
        quality = eval_image_quality(scene)
        print(f"   [M7] Image Quality:    {quality['original_sharpness']} -> {quality['enhanced_sharpness']} "
              f"(x{quality['improvement_ratio']}) | {quality['original_resolution']} -> {quality['enhanced_resolution']}")

        # Metric 8
        latency = eval_latency(scene)
        print(f"   [M8] Latency:          fetch={latency['fetch_sec']}s upscale={latency['upscale_sec']}s "
              f"ffmpeg={latency['ffmpeg_sec']}s total={latency['total_sec']}s")

        # Metric 9
        wpm = eval_speaking_rate(scene)
        print(f"   [M9] Speaking Rate:    {wpm['wpm']} WPM ({wpm['rating']}) | target: {wpm['target_wpm']} WPM")

        scene_result = {
            "scene_index": idx,
            "sentence": scene["sentence"],
            "av_sync": av_sync,
            "prompt_adherence": clip,
            "image_quality": quality,
            "latency": latency,
            "speaking_rate": wpm,
        }
        results["scenes"].append(scene_result)

        # Accumulate for averages
        if av_sync["sync_error_sec"] >= 0:
            sync_errors.append(av_sync["sync_error_sec"])
        if clip["score"] >= 0:
            clip_scores.append(clip["score"])
        if quality["improvement_ratio"] > 0:
            sharpness_improvements.append(quality["improvement_ratio"])
        if latency["fetch_sec"] >= 0:
            fetch_times.append(latency["fetch_sec"])
        if latency["upscale_sec"] >= 0:
            upscale_times.append(latency["upscale_sec"])
        if latency["ffmpeg_sec"] >= 0:
            ffmpeg_times.append(latency["ffmpeg_sec"])
        if wpm["wpm"] > 0:
            wpms.append(wpm["wpm"])

        print()

    # ── Compute averages ──────────────────────────────────────────────────────
    def safe_avg(lst):
        return round(sum(lst) / len(lst), 3) if lst else -1

    results["averages"] = {
        "avg_sync_error_sec": safe_avg(sync_errors),
        "avg_prompt_adherence": safe_avg(clip_scores),
        "avg_sharpness_improvement": safe_avg(sharpness_improvements),
        "avg_fetch_sec": safe_avg(fetch_times),
        "avg_upscale_sec": safe_avg(upscale_times),
        "avg_ffmpeg_sec": safe_avg(ffmpeg_times),
        "avg_wpm": safe_avg(wpms),
        "total_pipeline_sec": total_pipeline_sec,
    }

    # ── Print summary table ───────────────────────────────────────────────────
    avg = results["averages"]
    print(f"{'='*70}")
    print(f"  EVALUATION SUMMARY - {story_id}")
    print(f"{'='*70}")
    print(f"  M5  Avg AV Sync Error:       {avg['avg_sync_error_sec']}s")
    print(f"  M6  Avg Prompt Adherence:     {avg['avg_prompt_adherence']}")
    print(f"  M7  Avg Sharpness Improvement: ×{avg['avg_sharpness_improvement']}")
    print(f"  M8  Avg Latency (fetch):      {avg['avg_fetch_sec']}s")
    print(f"      Avg Latency (upscale):    {avg['avg_upscale_sec']}s")
    print(f"      Avg Latency (ffmpeg):     {avg['avg_ffmpeg_sec']}s")
    print(f"      Total Pipeline:           {avg['total_pipeline_sec']}s")
    print(f"  M9  Avg Speaking Rate:        {avg['avg_wpm']} WPM (target: 120-150)")
    print(f"{'='*70}")

    # ── Save results ──────────────────────────────────────────────────────────
    output_dir = os.path.dirname(eval_data_path)
    output_path = os.path.join(output_dir, "video_evaluation_results.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print(f"\n[OK] Results saved to: {output_path}")
    print(f"     Copy this into your FYP report!")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        # Auto-discover: find the most recent evaluation_data.json
        output_dir = os.path.join(os.path.dirname(SCRIPT_DIR), "output_videos")
        found = []
        if os.path.exists(output_dir):
            for d in os.listdir(output_dir):
                candidate = os.path.join(output_dir, d, "evaluation_data.json")
                if os.path.exists(candidate):
                    found.append(candidate)
        if found:
            # Sort by modification time, most recent first
            found.sort(key=lambda p: os.path.getmtime(p), reverse=True)
            print(f"[Auto] Found evaluation data: {found[0]}")
            main(found[0])
        else:
            print("Usage: python evaluate_video.py <path_to_evaluation_data.json>")
            print("       Or run generate_video.py first to create evaluation data.")
            sys.exit(1)
    else:
        main(sys.argv[1])
